---
title: "PLPA 6820 Final Project"
author: "SA Donohoo"
date: "2025-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

### 05 Population Structure Analyses - LEA Admixture
Genetic admixture among all lineages was assessed with the snmf function in the R package LEA (Frichot & François, 2015) using the single-snp datasets produced by STACKS because the *snmf* method assumes that SNPs are unlinked.

```{r 05_LEA_Admixture_Analysis, echo=TRUE, results = 'hide'}

# Load Packages
library(LEA)
library(BiocManager)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggrepel)

# Load data from Single SNP VCF produced by Stacks
Dutt.input.file <- "05_Population_Structure_Admixture/Duttoniana_min_max_NBA_Single.snps.vcf"

# Load in metadata for each Species
Dutt.Metadata <- read.csv("05_Population_Structure_Admixture/Duttoniana_Metadata.csv", header = TRUE, na.strings = "NA")

# Create a function that finds the best fit K-value for LEA Admixture Analysis.
Admixture.Lea.K.qmatrix <- function(Input.File, Kvalue){
  Geno <- vcf2geno(Input.File, force = TRUE)
  obj.snmf_100 = snmf(Geno, K = Kvalue, project = "new", alpha = 100, 
                      tolerance = 0.0000000001, repetitions = 10, 
                      entropy=TRUE, ploidy = 2)
  ce <- cross.entropy(obj.snmf_100, K = Kvalue)
  best <- which.min(ce)
  qmatrix <- Q(obj.snmf_100, K = Kvalue, run = best)
}

# Run LEA Admixture for Lithasia duttoniana in the Duck River, TN.
# Best fit K-value is 2.
Dutt.qmatrix.K2 <- Admixture.Lea.K.qmatrix(Dutt.input.file, 2)
```

```{r 05_LEA_Admixture_Analysis Part 2, echo=TRUE}
# Convert Vector into DataFrame
Dutt.qmatrix.K2 <- data.frame(Dutt.qmatrix.K2)

# Add Specimen Column from Metadata to Qmatrix for Future Joining
Dutt.qmatrix.K2$Specimen <- Dutt.Metadata$Specimen

# Combine with Metadata DataFrame
Dutt.LEA.K2.Join <- full_join(Dutt.Metadata, Dutt.qmatrix.K2, by = "Specimen")

# Convert from Wide to Long Format
Dutt.LEA.K2.Long <- Dutt.LEA.K2.Join %>% 
  pivot_longer(
    cols = `V1`:`V2`, 
    names_to = "Admixure",
    values_to = "Amount"
  )

# Convert the Column Site into a Factor to Allow for Faceting
Dutt.LEA.K2.Long$Site <- as.factor(Dutt.LEA.K2.Long$Site)

# Using Levels, Reorder Sites so They Run Downstream to UpStream
Dutt.LEA.K2.Long$Site <- factor(Dutt.LEA.K2.Long$Site, levels = c("Dyer",
                                                                      "NV",
                                                                      "CV",
                                                                      "KM",
                                                                      "B",
                                                                      "IP",
                                                                      "HWY412",
                                                                      "R",
                                                                      "IB",
                                                                      "SP",
                                                                      "FW",
                                                                      "SM",
                                                                      "CB",
                                                                      "HM",
                                                                      "HWY31",
                                                                      "WB"
))

# Create a Color-Blind Friendly Palette
cbbPalette <- c("#56B4E9","#E69F00", "#0072B2", "#009E73", "#F0E442", "#D55E00", "#CC79A7")

# Graph the Admixture Results. Use Facet to Split into Sections by Site
Dutt.admixture <- ggplot(Dutt.LEA.K2.Long, aes(x = factor(Specimen), y = Amount, fill = Admixure)) +
  geom_col(width = 1) +
  # Facet over the groups
  facet_grid(~ Site, switch = "x", scales = "free", space = "free") +
  # Use these expand arguments to get rid of padding around the axes
  scale_x_discrete(expand = c(0,0), name = "Lithasia duttoniana Sites") +
  scale_y_continuous(expand = c(0,0), name = "Admixture Coefficients") +
  scale_fill_manual(values = (cbbPalette), name = "") +
  # We're hiding most of the x-axis and the spacing between panels
  theme(panel.spacing.x = grid::unit(0.05, "cm"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"),
        legend.position="")
```

#### Results of LEA Admixture Analysis for *Lithasia duttoniana*

```{r 05_LEA_Admixture_Analysis Part 3, echo=FALSE}
# View Admixture Graph
Dutt.admixture
```
